import { useMemo, useState, type FormEvent } from 'react';
import { Mail, Pencil, Plus, Search, Trash2, Users, X } from 'lucide-react';
import { useInvoices, formatMoney } from '@/lib/invoice-data';

type ClientForm = { name: string; email: string; company: string };

export default function Clients() {
  const { clients, invoices, addClient, updateClient, deleteClient } = useInvoices();
  const [query, setQuery] = useState('');
  const [editing, setEditing] = useState<string | null>(null);
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState<ClientForm>({ name: '', email: '', company: '' });
  const shown = useMemo(() => clients.filter((client) => `${client.name} ${client.company} ${client.email}`.toLowerCase().includes(query.toLowerCase())), [clients, query]);
  const openAdd = () => { setForm({ name: '', email: '', company: '' }); setEditing(null); setShowForm(true); };
  const openEdit = (id: string) => { const client = clients.find((item) => item.id === id); if (client) { setForm({ name: client.name, email: client.email, company: client.company }); setEditing(id); setShowForm(true); } };
  const save = (event: FormEvent) => { event.preventDefault(); editing ? updateClient(editing, form) : addClient(form); setShowForm(false); };
  return <div className="mx-auto max-w-[1180px] px-5 py-8 md:px-10 md:py-11">
    <div className="animate-rise mb-9 flex flex-wrap items-end justify-between gap-5"><div><p className="font-data text-[10px] uppercase tracking-[.2em] text-accent">Relationships</p><h1 className="mt-2 font-display text-4xl tracking-[-.045em] sm:text-5xl">Your people.</h1><p className="mt-3 text-sm text-muted-foreground">The humans behind the line items.</p></div><button onClick={openAdd} className="flex items-center gap-2 rounded-lg bg-accent px-4 py-3 text-sm font-bold text-accent-foreground transition-transform hover:-translate-y-0.5" data-testid="button-add-client"><Plus size={16} /> Add client</button></div>
    <div className="mb-6 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2 text-xs text-muted-foreground"><Users size={15} /> {clients.length} active clients</div><div className="relative w-full sm:w-64"><Search size={15} className="absolute left-3 top-3 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} className="h-10 w-full rounded-lg border border-input bg-card pl-9 pr-3 text-xs outline-none focus:border-accent focus:ring-2 focus:ring-accent/15" placeholder="Search people..." data-testid="input-search-clients" /></div></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{shown.map((client, index) => { const clientInvoices = invoices.filter((invoice) => invoice.clientId === client.id); const billed = clientInvoices.length ? clientInvoices.reduce((sum, invoice) => sum + invoice.items.reduce((total, item) => total + item.quantity * item.unitPrice, 0), 0) : client.totalBilled; return <article key={client.id} className={`animate-rise rounded-xl border border-card-border bg-card p-5 soft-shadow transition-all hover:-translate-y-0.5 hover:border-accent/50 stagger-${Math.min(index + 1, 3)}`} data-testid={`card-client-${client.id}`}><div className="mb-6 flex items-start justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-secondary font-display text-lg text-secondary-foreground">{client.name.split(' ').map((part) => part[0]).join('')}</div><div className="flex gap-1"><button onClick={() => openEdit(client.id)} className="rounded-md p-2 text-muted-foreground hover:bg-muted hover:text-primary" data-testid={`button-edit-client-${client.id}`}><Pencil size={14} /></button><button onClick={() => { if (window.confirm(`Remove ${client.name} from your clients?`)) deleteClient(client.id); }} className="rounded-md p-2 text-muted-foreground hover:bg-[#f8dcd5] hover:text-[#a14232]" data-testid={`button-delete-client-${client.id}`}><Trash2 size={14} /></button></div></div><h2 className="font-display text-2xl tracking-[-.025em]">{client.company}</h2><p className="mt-1 text-sm font-semibold">{client.name}</p><p className="mt-1 flex items-center gap-1.5 text-xs text-muted-foreground"><Mail size={13} /> {client.email}</p><div className="mt-6 flex items-end justify-between border-t border-border pt-4"><div><p className="font-data text-[10px] uppercase tracking-[.12em] text-muted-foreground">Billed to date</p><p className="mt-1 font-data text-sm">{formatMoney(billed)}</p></div><div className="text-right"><p className="font-data text-[10px] uppercase tracking-[.12em] text-muted-foreground">Invoices</p><p className="mt-1 font-data text-sm">{clientInvoices.length || client.invoices}</p></div></div></article>; })}</div>
    {shown.length === 0 && <div className="rounded-xl border border-dashed border-border bg-card/50 py-16 text-center"><p className="font-display text-2xl">No one by that name.</p><p className="mt-2 text-sm text-muted-foreground">Try a different search or add a new client.</p></div>}
    {showForm && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#172035]/35 p-5" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-2xl border border-card-border bg-card p-6 paper-shadow"><div className="mb-6 flex items-start justify-between"><div><p className="font-data text-[10px] uppercase tracking-[.18em] text-accent">Client details</p><h2 className="mt-1 font-display text-3xl">{editing ? 'Edit client.' : 'Add a client.'}</h2></div><button onClick={() => setShowForm(false)} className="rounded-md p-2 text-muted-foreground hover:bg-muted" data-testid="button-close-client-form"><X size={18} /></button></div><form onSubmit={save} className="space-y-4"><label className="block text-xs font-semibold text-muted-foreground">Company name<input required value={form.company} onChange={(e) => setForm({ ...form, company: e.target.value })} className="mt-2 h-11 w-full rounded-lg border border-input bg-background px-3 text-sm outline-none focus:border-accent" placeholder="Northstar Studio" data-testid="input-client-company" /></label><label className="block text-xs font-semibold text-muted-foreground">Contact name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="mt-2 h-11 w-full rounded-lg border border-input bg-background px-3 text-sm outline-none focus:border-accent" placeholder="Maya Chen" data-testid="input-manage-client-name" /></label><label className="block text-xs font-semibold text-muted-foreground">Email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="mt-2 h-11 w-full rounded-lg border border-input bg-background px-3 text-sm outline-none focus:border-accent" placeholder="maya@studio.com" data-testid="input-manage-client-email" /></label><button type="submit" className="mt-3 flex w-full items-center justify-center rounded-lg bg-primary px-4 py-3 text-sm font-bold text-primary-foreground hover:bg-primary/90" data-testid="button-save-client">{editing ? 'Save changes' : 'Add client'}</button></form></div></div>}
  </div>;
}