import { useMemo, useState } from 'react';
import { ArrowDownRight, ArrowUpRight, CircleDollarSign, Filter, Search, TrendingUp } from 'lucide-react';
import { Link } from 'wouter';
import { InvoiceCard } from '@/components/invoice-card';
import { InvoiceTable } from '@/components/invoice-table';
import { formatMoney, invoiceTotal, useInvoices, type InvoiceStatus } from '@/lib/invoice-data';

export default function Dashboard() {
  const { invoices, markPaid, deleteInvoice } = useInvoices();
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState<'All' | InvoiceStatus>('All');
  const filtered = useMemo(() => invoices.filter((invoice) => {
    const matchesQuery = `${invoice.clientName} ${invoice.number}`.toLowerCase().includes(query.toLowerCase());
    return matchesQuery && (status === 'All' || invoice.status === status);
  }), [invoices, query, status]);
  const paid = invoices.filter((item) => item.status === 'Paid').reduce((sum, item) => sum + invoiceTotal(item), 0);
  const outstanding = invoices.filter((item) => item.status !== 'Paid').reduce((sum, item) => sum + invoiceTotal(item), 0);
  const overdue = invoices.filter((item) => item.status === 'Overdue').reduce((sum, item) => sum + invoiceTotal(item), 0);
  const handleDelete = (id: string) => { if (window.confirm('Delete this invoice? This cannot be undone.')) deleteInvoice(id); };
  return <div className="mx-auto max-w-[1320px] px-5 py-8 md:px-10 md:py-11">
    <div className="animate-rise mb-9 flex flex-wrap items-end justify-between gap-5"><div><p className="font-data text-[10px] uppercase tracking-[.2em] text-accent">Tuesday, June 18</p><h1 className="mt-2 font-display text-[38px] leading-none tracking-[-.045em] sm:text-5xl">Good morning, Alex.</h1><p className="mt-3 text-sm text-muted-foreground">Here’s the pulse of your studio.</p></div><Link href="/invoices/new" className="group flex items-center gap-2 rounded-lg bg-accent px-4 py-3 text-sm font-bold text-accent-foreground transition-transform hover:-translate-y-0.5" data-testid="link-create-invoice"><span className="text-lg leading-none">+</span> Create an invoice <ArrowUpRight size={15} className="transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></Link></div>
    <div className="animate-rise stagger-1 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-card-border bg-card p-5 soft-shadow"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-muted-foreground">Collected this season</p><CircleDollarSign size={17} className="text-secondary-foreground" /></div><p className="mt-4 font-data text-2xl">{formatMoney(paid)}</p><p className="mt-2 flex items-center gap-1 text-[11px] text-[#286354]"><TrendingUp size={12} /> 12.4% from last season</p></div><div className="rounded-xl border border-card-border bg-card p-5 soft-shadow"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-muted-foreground">Awaiting payment</p><ArrowUpRight size={17} className="text-[#89641d]" /></div><p className="mt-4 font-data text-2xl">{formatMoney(outstanding)}</p><p className="mt-2 text-[11px] text-muted-foreground">{invoices.filter((i) => i.status !== 'Paid').length} invoices in motion</p></div><div className="rounded-xl border border-[#f0d5ce] bg-[#fff4f0] p-5 soft-shadow"><div className="flex items-center justify-between"><p className="text-xs font-semibold text-[#9c4b3c]">Needs your eye</p><ArrowDownRight size={17} className="text-[#b45a48]" /></div><p className="mt-4 font-data text-2xl text-[#8f4033]">{formatMoney(overdue)}</p><p className="mt-2 text-[11px] text-[#a26358]">{invoices.filter((i) => i.status === 'Overdue').length} overdue invoice</p></div></div>
    <section className="animate-rise stagger-2 mt-10"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-2xl tracking-[-.025em]">Your invoices</h2><p className="mt-1 text-xs text-muted-foreground">{filtered.length} of {invoices.length} invoices</p></div><div className="flex w-full gap-2 sm:w-auto"><div className="relative min-w-0 flex-1 sm:w-56"><Search size={15} className="absolute left-3 top-3 text-muted-foreground" /><input type="search" value={query} onChange={(e) => setQuery(e.target.value)} className="h-10 w-full rounded-lg border border-input bg-card pl-9 pr-3 text-xs outline-none focus:border-accent focus:ring-2 focus:ring-accent/15" placeholder="Search invoices..." data-testid="input-search-invoices" /></div><label className="relative"><Filter size={14} className="pointer-events-none absolute left-3 top-3 text-muted-foreground" /><select value={status} onChange={(e) => setStatus(e.target.value as 'All' | InvoiceStatus)} className="h-10 appearance-none rounded-lg border border-input bg-card pl-8 pr-8 text-xs font-semibold outline-none focus:border-accent" data-testid="select-status-filter"><option value="All">All statuses</option><option value="Paid">Paid</option><option value="Pending">Pending</option><option value="Overdue">Overdue</option></select></label></div></div><InvoiceTable invoices={filtered} onMarkPaid={markPaid} onDelete={handleDelete} /><div className="grid gap-3 sm:grid-cols-2 md:hidden">{filtered.map((invoice) => <InvoiceCard key={invoice.id} invoice={invoice} onMarkPaid={markPaid} />)}</div>{filtered.length === 0 && <div className="rounded-xl border border-dashed border-border bg-card/50 py-16 text-center"><p className="font-display text-2xl">Nothing matches that search.</p><p className="mt-2 text-sm text-muted-foreground">Try another client or clear the filter.</p></div>}</section>
  </div>;
}