import { ArrowLeft, Download, Mail, Pencil, Printer } from 'lucide-react';
import { Link } from 'wouter';
import { formatDate, formatMoney, invoiceSubtotal, invoiceTax, invoiceTotal, type Invoice } from '@/lib/invoice-data';
import { StatusBadge } from '@/components/status-badge';

export function InvoicePreview({ invoice, onMarkPaid }: { invoice: Invoice; onMarkPaid: () => void }) {
  return <div className="mx-auto max-w-[920px]">
    <div className="no-print mb-6 flex flex-wrap items-center justify-between gap-3"><Link href="/" className="flex items-center gap-2 text-xs font-semibold text-muted-foreground hover:text-primary" data-testid="link-back-dashboard"><ArrowLeft size={15} /> Back to overview</Link><div className="flex gap-2"><Link href={`/invoices/${invoice.id}/edit`} className="flex items-center gap-2 rounded-lg border border-border bg-card px-3 py-2 text-xs font-semibold hover:border-accent hover:text-accent" data-testid="link-edit-detail"><Pencil size={14} /> Edit</Link><button onClick={() => window.print()} className="flex items-center gap-2 rounded-lg border border-border bg-card px-3 py-2 text-xs font-semibold hover:border-accent hover:text-accent" data-testid="button-print-invoice"><Printer size={14} /> Print / PDF</button><button onClick={() => { navigator.clipboard?.writeText(invoice.clientEmail); window.alert(`Ready to email ${invoice.clientName}`); }} className="flex items-center gap-2 rounded-lg bg-primary px-3 py-2 text-xs font-semibold text-primary-foreground hover:bg-primary/90" data-testid="button-email-invoice"><Mail size={14} /> Send reminder</button></div></div>
    <div className="invoice-paper overflow-hidden rounded-xl border border-card-border bg-card paper-shadow">
      <div className="flex flex-wrap items-start justify-between gap-8 border-b border-border p-7 sm:p-12"><div><div className="mb-10 flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-accent text-accent-foreground"><Download size={15} /></span><span className="font-display text-xl">ledgerly</span></div><p className="font-data text-[10px] uppercase tracking-[.18em] text-muted-foreground">Invoice from</p><p className="mt-2 text-sm font-semibold">Alex Rivera Studio</p><p className="mt-1 max-w-[180px] text-xs leading-relaxed text-muted-foreground">Brooklyn, NY<br />alex@rivera.studio</p></div><div className="text-left sm:text-right"><p className="font-data text-xs text-muted-foreground">{invoice.number}</p><h1 className="mt-1 font-display text-4xl tracking-[-.04em] sm:text-5xl">Invoice</h1><div className="mt-5 sm:flex sm:justify-end"><StatusBadge status={invoice.status} /></div></div></div>
      <div className="grid gap-8 border-b border-border p-7 sm:grid-cols-3 sm:p-12"><div><p className="font-data text-[10px] uppercase tracking-[.18em] text-muted-foreground">Billed to</p><p className="mt-3 text-sm font-semibold">{invoice.clientName}</p><p className="mt-1 text-xs text-muted-foreground">{invoice.clientEmail}</p></div><div><p className="font-data text-[10px] uppercase tracking-[.18em] text-muted-foreground">Issued</p><p className="mt-3 text-sm font-semibold">{formatDate(invoice.issueDate)}</p></div><div><p className="font-data text-[10px] uppercase tracking-[.18em] text-muted-foreground">Due</p><p className="mt-3 text-sm font-semibold">{formatDate(invoice.dueDate)}</p></div></div>
      <div className="p-7 sm:p-12"><div className="overflow-x-auto"><table className="w-full min-w-[500px]"><thead><tr className="border-b-2 border-primary text-left font-data text-[10px] uppercase tracking-[.15em] text-muted-foreground"><th className="pb-3">Description</th><th className="pb-3 text-right">Qty</th><th className="pb-3 text-right">Rate</th><th className="pb-3 text-right">Amount</th></tr></thead><tbody>{invoice.items.map((item) => <tr key={item.id} className="border-b border-border/70 text-sm"><td className="py-5 font-medium">{item.description || 'Untitled service'}</td><td className="py-5 text-right font-data text-xs">{item.quantity}</td><td className="py-5 text-right font-data text-xs">{formatMoney(item.unitPrice)}</td><td className="py-5 text-right font-data text-xs">{formatMoney(item.quantity * item.unitPrice)}</td></tr>)}</tbody></table></div>
        <div className="ml-auto mt-8 w-full max-w-[280px] space-y-3 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Subtotal</span><span className="font-data text-xs">{formatMoney(invoiceSubtotal(invoice))}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Tax ({invoice.taxRate}%)</span><span className="font-data text-xs">{formatMoney(invoiceTax(invoice))}</span></div><div className="flex justify-between border-t border-primary pt-4 text-base font-semibold"><span>Total due</span><span className="font-data">{formatMoney(invoiceTotal(invoice))}</span></div></div>
        <div className="mt-16 grid gap-8 border-t border-border pt-6 sm:grid-cols-[1fr_240px]"><div><p className="font-data text-[10px] uppercase tracking-[.18em] text-muted-foreground">Note</p><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{invoice.notes || 'Thank you for your business.'}</p></div>{invoice.status !== 'Paid' && <button onClick={onMarkPaid} className="no-print self-start rounded-lg bg-secondary px-4 py-2.5 text-xs font-semibold text-secondary-foreground hover:bg-secondary/80" data-testid="button-mark-detail-paid">Mark invoice as paid</button>}</div>
      </div>
    </div>
  </div>;
}